users:
  - username: brice
    password: "$6$randomhash1"
    emp_id: EMP003
    department: DevOps
    pub_key: "files/keys/brice.pub"

  - username: denis
    password: "$6$randomhash2"
    emp_id: EMP004
    department: Cloud
    pub_key: "files/keys/denis.pub"

  - username: prof
    password: "$6$randomhash2"
    emp_id: EMP005
    department: Cloud
    pub_key: "files/keys/prof.pub"

  - username: edmond
    password: "$6$randomhash2"
    emp_id: EMP006
    department: Cloud
    pub_key: "files/keys/edmond.pub"

  - username: anold
    password: "$6$randomhash2"
    emp_id: EMP006
    department: Cloud
    pub_key: "files/keys/anold.pub"

  - username: yannko
    password: "$6$randomhash2"
    emp_id: EMP007
    department: Cloud
    pub_key: "files/keys/yannko.pub"